[package]
name = "gst-plugin-ndi"
version = "1.0.0"
authors = ["Ruben Gonzalez <rubenrua@teltek.es>", "Daniel Vilar <daniel.peiteado@teltek.es>"]
repository = "https://github.com/teltek/gst-plugin-ndi"
build = "build.rs"
license = "LGPL"

[dependencies]
glib = { version = "0.7.1", features = ["subclassing"] }
gstreamer = { version = "0.13.0", features = ["subclassing"] }
gstreamer-base = { version = "0.13.0", features = ["subclassing"] }
gstreamer-audio = "0.13.0"
gstreamer-video = "0.13.0"
lazy_static = "1.1.0"
byte-slice-cast = "0.2.0"

[lib]
name = "gstndi"
crate-type = ["cdylib"]
path = "src/lib.rs"
